### ISSUE TITLE
Akhirnya, gue tau cara emulate android yang cepet..

### ISSUE THREAD

**Issue by jurnalanas** [jurnalanas/Gizr#2]
Lu coba nanti download sdk lagi di http://developer.android.com/sdk/index.html, bikin folderr baru di C:\android, terus extract disitu.. abis itu download www.genymotion.com..

![8-9-2013 1-03-46 pm](https://f.cloud.github.com/assets/876900/936599/e8093d0e-00ba-11e3-90b0-368c8f261c8d.png)
![8-9-2013 1-03-03 pm](https://f.cloud.github.com/assets/876900/936600/e8367d3c-00ba-11e3-88e1-f84c84814975.png)
![8-9-2013 1-04-11 pm](https://f.cloud.github.com/assets/876900/936601/e84296d0-00ba-11e3-8775-e55ad34ffb02.png)

**Comment by ghost** [comment]
udah selesei cuy @jurnalanas
